Update patch set 3
Patch Set 3:

The build failure is
java.lang.NoClassDefFoundError: org/eclipse/jgit/errors/AmbiguousObjectException

This does not seem to be caused by the change.

Patch-set: 3
Reviewer: Gerrit User 12380 <12380@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Verified=0