Update patch set 2
Patch Set 2:

It is very nice to have a possibility to use LLDB as a back end debugger, 
and re-using most of the dsf-gdb functionality :-)

Here goes a list of findings with a round of testing:

* View memory action, from the context menu, throw exception
* Similarly using an expression to a variable name gets the same exception but not when using it as an address
* Variables view, pointer variable / string variables sometimes do not resolve, so the variables view "Value"  column display a red message i.e.
        -var-create - * hbReceivingThreadName
        Error message from debugger back end:
        error: error: use of undeclared identifier 'hbReceivingThreadName'\nerror: 1 errors parsing expression\n
* Variables view not always populates locals, e.g. tried with a multi-thread program, letting it run,
        inserted a break point while running, when it stops re-select back the main method, I see no locals in the variables view
* Introduce a minimum LLDB version supported i.e. forcing the adopters to use the latest LLDB when using this experimental feature.
* Run to line not working (i.e. does not stop)
* Move to Line not working "Move To Line failed"
* Resume at Line not working "Resume At Line failed"
* Step into selection, not stopping
* Disconnect, does not seem to react (I guess it does not make a big difference, it seems useful for multi-process ?)
* Some error messages are displayed when trying using the console although it works when issuing MI commands
* Registers not updated when selecting each frame e.g.the stack pointer for x86_64 "rsp"

with Assertions enabled, I get:
* At session start, getting IllegalStateException, done() method called more than once
* At termination we get an exceptions:
        Caused by: java.lang.AssertionError
        at org.eclipse.cdt.dsf.gdb.service.GDBProcesses_7_0.eventDispatched(GDBProcesses_7_0.java:1854)
        at org.eclipse.cdt.dsf.gdb.service.GDBProcesses_7_2.eventDispatched(GDBProcesses_7_2.java:739)
* Stepping feels a bit slow
* Multi-core visualizer not working, i.e. no threads displayed
* 'cores' or 'thread names' are not displayed next to each process or  thread node
* Any way to support pretty printing ?

The code looks well structured, I still need to do a more detailed review, more comments will follow.

Thanks Marc-Andre!

Patch-set: 2
Reviewer: Gerrit User 482 <482@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Verified=0