Update patch set 1
Patch Set 1:

> I don't understand what's going on here. The tests are throwing
 > NoClassDefFoundErrors and such, and I don't see how anything in the
 > patch could cause that.

:-( I don't get it either. My suspicion is that there is something unclean in the workspace. The workspace is not cleaned with each build, but I am going to do that manually now. I believe that when we get and move to the new build infrastructure from Eclipse then we will be changing some of these builds to be much cleaner.

Patch-set: 1