Bug 536023: NoClassDefFoundError for javax/xml/bind/DatatypeConverter
This package is marked for removal in Java 10 and in fact, is not found at
run time. Instead, use the javax.xml.bin plugin from Orbit.

javax.xml.stream is also needed by javax.xml.bind.

Change-Id: Ida10746267c814a8a11f2db7181dcb9e8ceaad44
Signed-off-by: Marc-Andre Laperle <marc-andre.laperle@ericsson.com>