Update patch set 2
Patch Set 2:

Hi Jonah,

There might be something wrong in my setup, but I get a consistent failure, for testcase "CommandTimeoutTest", with or without your patch (running in my development environment). It's one of 2 failing tests, I seem to get all the time, running the whole test suite.

I also get the same error, running the test in isolation, so it might be a different issue, than the one you're trying to fix? 

java.lang.AssertionError: Unexpected exception
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.eclipse.cdt.tests.dsf.gdb.tests.CommandTimeoutTest.processException(CommandTimeoutTest.java:176)
	at org.eclipse.cdt.tests.dsf.gdb.tests.CommandTimeoutTest.commandTimedOutDuringLaunch(CommandTimeoutTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

Patch-set: 2
Reviewer: Gerrit User 938 <938@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Verified=0