Bug 540699 - NoClassDefFoundError in AutotoolsNewMakeGenerator
- use of CommandLaunchManager requires higher version of cdt.core
  than Autotools specified so up to 6.5.0

Change-Id: I315e69defeee9d7d1e6c016edff2d96013fe13e9