Update patch set 3
Patch Set 3:

I don't understand what's going on here. The tests are throwing NoClassDefFoundErrors and such, and I don't see how anything in the patch could cause that.

Patch-set: 3
Label: Verified=0