Update patch set 2
Patch Set 2: (1 inline comment)

I started getting an exception in the expressions view which I traced back to a missing 'return' in this bug.


java.lang.IllegalStateException: RequestMonitor: RequestMonitor (org.eclipse.cdt.dsf.ui.viewmodel.DefaultVMModelProxyStrategy$11$2@95c13b): Status OK: unknown code=0 OK null, done() method called more than once
	at org.eclipse.cdt.dsf.concurrent.RequestMonitor.done(RequestMonitor.java:285)

Patch-set: 2