Bug 529386 - NoSuchMethodError in AutotoolsNewMakeGenerator.runScript
- bump up org.eclipse.cdt.remote.core so that autotools.core
  can refer to the latest version in its dependencies

Change-Id: I4ec198d7c5d367a4a479a1dd39839f3c2d8c4a96
(cherry picked from commit 7050f18ecf8304191295d65d0f516a829575534f)