Update patch set 7
Patch Set 7: (2 inline comments)

I'm very happy with the current behavior of this new view.  We covered everything I can think of.

I've seen some NPEs sometimes which we should guard against, but I don't see any major problems.

1- Sorting columns seems to have broken.  Clicking on a column gives multiple of the following NPEs:
java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
    at java.util.ArrayList.RangeCheck(ArrayList.java:547)
    at java.util.ArrayList.get(ArrayList.java:322)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSData.getColumnText(OSData.java:123)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.ContentLabelProviderWrapper.getColumnText(ContentLabelProviderWrapper.java:67)
    at org.eclipse.jface.viewers.TableColumnViewerLabelProvider.update(TableColumnViewerLabelProvider.java:70)

2- Starting a session and choosing a different resource to display from the drop down gave me this NPE:
Caused by: java.lang.NullPointerException
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.populateViewMenu(OSResourcesView.java:536)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.showTable(OSResourcesView.java:400)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.update(OSResourcesView.java:365)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.access$3(OSResourcesView.java:294)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView$6.update(OSResourcesView.java:271)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.SessionOSData$3.run(SessionOSData.java:231)

3- I also saw another NPE once in a while:
java.lang.NullPointerException
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.ResourceClassContributionItem.updateClasses(ResourceClassContributionItem.java:96)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.update(OSResourcesView.java:309)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.setDebugContext(OSResourcesView.java:282)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.setDebugContext(OSResourcesView.java:245)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.setupContextListener(OSResourcesView.java:198)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.createPartControl(OSResourcesView.java:177)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:129)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:300)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)

4- The view menu seems broken.  When I remove a column, the column stays, but when I try to add it, it adds a new duplicate one.

5- If I scroll down the view and then change the debug context (but stay in the same launch) the view scrolls back to the top.  I think it would be more user-friendly to not change the view at all.  Maybe it is as simple as noticing that the context change can be ignored since the ICommandControlDMContext is the same.

6- I got this NPE when switching from one launch to antoher sometimes.  I might have screwed up my launch, but it shows that it could happen:
java.lang.NullPointerException
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.setDebugContext(OSResourcesView.java:256)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.setDebugContext(OSResourcesView.java:245)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView.access$4(OSResourcesView.java:214)
    at org.eclipse.cdt.dsf.gdb.internal.ui.osview.OSResourcesView$4.debugContextChanged(OSResourcesView.java:193)
    at org.eclipse.debug.internal.ui.contexts.DebugWindowContextService$1.run(DebugWindowContextService.java:212)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.debug.internal.ui.contexts.DebugWindowContextService.notify(DebugWindowContextService.java:210)
    at org.eclipse.debug.internal.ui.contexts.DebugWindowContextService.notify(DebugWindowContextService.java:185)
    at org.eclipse.debug.internal.ui.contexts.DebugWindowContextService.debugContextChanged(DebugWindowContextService.java:408)
    at org.eclipse.debug.ui.contexts.AbstractDebugContextProvider$1.run(AbstractDebugContextProvider.java:79)

7- In all-stop mode, I like how the menus become grayed out when the target is not available.  However, the 'fetch' link remains usable, which will trigger a "Fething data..." which will only complete once the inferior is interrupted

8- If there are multiple debug contexts selected,  the code choosed the first one arbitrarily.  This is not clear to the user. I suggest one of two things:
  a) If all selected contexts have the same parent ICommandControlDMContext, then display resources as done now using any one context. If the parents are different, then disable and empty the view 
or 
  b) Always disable and empty the view for multi-selection

9- The case where -info-os returns an error does not seem to be handled properly.  For example, if I have the OSResources view open when using a post-mortem session (core file), GDB gives:
   448,664 [MI]  24-info-os
   448,666 [MI]  24^error,msg="Can not fetch data now."
   or
   600,684 [MI]  25-info-os modules
   600,686 [MI]  25^error,msg="Can not fetch data now."

But the view is stuck showing "Determining available OS resource classes..." or "Fetching data..." depending on the timing.


10- One time I got the following reply from GDB (maybe my gdbserver was wrong), but it caused an NPE that I think we should guard against:
   915,516 [MI]  42-info-os semaphores
   921,522 [MI]  ~"Ignoring packet error, continuing...\n"
   921,523 [MI]  42^error,msg="Can not fetch data now."
Exception in thread "MI RX Thread" java.lang.NullPointerException
    at org.eclipse.cdt.dsf.mi.service.command.output.MIInfoOsInfo.get(MIInfoOsInfo.java:173)
    at org.eclipse.cdt.dsf.mi.service.command.output.MIInfoOsInfo.parseResourcesInformation(MIInfoOsInfo.java:128)
    at org.eclipse.cdt.dsf.mi.service.command.output.MIInfoOsInfo.<init>(MIInfoOsInfo.java:75)
    at org.eclipse.cdt.dsf.mi.service.command.commands.MIInfoOs.getResult(MIInfoOs.java:47)
    at org.eclipse.cdt.dsf.mi.service.command.commands.MIInfoOs.getResult(MIInfoOs.java:1)
    at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:907)
    at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:754)

11- The new osresources.gif icon should go under the view16 folder and should be renamed to osresources_view.gif,
    i.e., dsf-gdb/org.eclipse.cdt.dsf.gdb.ui/icons/full/view16/osresources_view.gif
    Don't forget to update the plugin.xml file to match

12- In MANIFEST.MF, please export the new osview package, as the other packages are exported

Patch-set: 7