Update patch set 4
Patch Set 4:

Reverted commit since it triggers java.lang.IllegalArgumentException: X is not a member of Y
at org.eclipse.cdt.internal.core.dom.parser.cpp.ClassTypeHelper.getVisibility(ClassTypeHelper.java:1001)

More details in bug 408314.

Patch-set: 4