Update patch set 6
Patch Set 6:

I've tested the patch on my code base. It causes a number of "X is not a member o Y" IllegalArgumentExceptions with a typical stack:
java.lang.IllegalArgumentException: X is not a member o Y
	at org.eclipse.cdt.internal.core.dom.parser.cpp.ClassTypeHelper.getVisibility(ClassTypeHelper.java:990)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPClassType.getVisibility(CPPClassType.java:423)
	at org.eclipse.cdt.internal.core.pdom.dom.cpp.PDOMCPPLinkage.addMember(PDOMCPPLinkage.java:405)

Patch-set: 6