Update patch set 2
Patch Set 2:

> > Build Failed
 > >
 > > https://ci.eclipse.org/cdt/job/cdt-verify-code-cleanliness-pipeline/1205/
 > > : FAILURE. The code base is not clean. This means one or more of
 > > formatting, whitespace, version numbers or other checks appears
 > to
 > > have failed. Please see the console output for details and
 > > https://github.com/eclipse-cdt/cdt-infra/tree/master/jenkins/pipelines/cdt/verify#cdt-verify-code-cleanliness
 > > for documentation on what is checked.
 > >
 > > https://ci.eclipse.org/cdt/job/cdt-verify-test-cdt-other-pipeline/1642/
 > > : FAILURE
 > >
 > > https://ci.eclipse.org/cdt/job/cdt-verify-test-cdt-ui-only-pipeline/1563/
 > > : SUCCESS
 > 
 > Receiving objects:  91% (685940/750877), 149.29 MiB | 3.80 MiB/s
 > error: index-pack died of signal 9

The error has come up many times before, but the difference now is that it is happening after only a minute or so, rather than because of 10 minute timeout.

If it continues happening regularly we'll have to raise a new bugzilla.

Patch-set: 2