Update patch set 12
Patch Set 12:

Note, there is a potential conflict with the use of IntermittentRule with this change, I have created a new Bug 508642 to cover that case. If for example you notice a trace like the following one then we have the problem.

    java.lang.Exception: Timed out waiting for ServiceEvent: org.eclipse.cdt.dsf.mi.service.command.events.MIStoppedEvent
	at org.eclipse.cdt.tests.dsf.gdb.framework.ServiceEventWaitor.waitForEvent(ServiceEventWaitor.java:145)
	at org.eclipse.cdt.tests.dsf.gdb.framework.SyncUtil.step(SyncUtil.java:178)
	at org.eclipse.cdt.tests.dsf.gdb.framework.SyncUtil.step(SyncUtil.java:142)
	at org.eclipse.cdt.tests.dsf.gdb.framework.SyncUtil.step(SyncUtil.java:131)
	at org.eclipse.cdt.tests.dsf.gdb.tests.LaunchConfigurationAndRestartTest.testStopAtMainWithReverse(LaunchConfigurationAndRestartTest.java:789)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

Patch-set: 12