Update patch set 7
Patch Set 7:

This doesn't compile on Darwin (OSX) because it uses an optional part of POSIX (Advanced Realtime Threads)

http://stackoverflow.com/questions/8920803/pthread-and-gcc-compiling-issue-on-os-x

I'm not saying it should block this patch but something to be aware of. Also, pthread_setname_np only takes one argument (const char*), I'm assuming it only changes the name of the current thread?

In file included from MultiThread.cc:5:
In file included from ./Thread.h:13:
./ThreadPthreadTypes.h:9:9: error: unknown type name 'pthread_barrier_t'
typedef pthread_barrier_t ThreadBarrier;
        ^
In file included from MultiThread.cc:5:
In file included from ./Thread.h:44:
./ThreadPthread.h:24:9: error: use of undeclared identifier 'pthread_barrier_init'
        return pthread_barrier_init(barrier, NULL, count) == 0;
               ^
./ThreadPthread.h:29:9: error: use of undeclared identifier 'pthread_barrier_destroy'; did you mean
      'pthread_attr_destroy'?
        return pthread_barrier_destroy(barrier) == 0;
               ^~~~~~~~~~~~~~~~~~~~~~~
               pthread_attr_destroy
/usr/include/pthread.h:213:5: note: 'pthread_attr_destroy' declared here
int pthread_attr_destroy(pthread_attr_t *);
    ^
In file included from MultiThread.cc:5:
In file included from ./Thread.h:44:
./ThreadPthread.h:29:33: error: cannot initialize a parameter of type 'pthread_attr_t *'
      (aka '_opaque_pthread_attr_t *') with an lvalue of type 'ThreadBarrier *' (aka 'int *')
        return pthread_barrier_destroy(barrier) == 0;
                                       ^~~~~~~
/usr/include/pthread.h:213:42: note: passing argument to parameter here
int pthread_attr_destroy(pthread_attr_t *);
                                         ^
In file included from MultiThread.cc:5:
In file included from ./Thread.h:44:
./ThreadPthread.h:35:8: error: use of undeclared identifier 'pthread_barrier_wait'; did you mean
      'ThreadBarrierWait'?
        ret = pthread_barrier_wait(barrier);
              ^~~~~~~~~~~~~~~~~~~~
              ThreadBarrierWait
./ThreadPthread.h:32:12: note: 'ThreadBarrierWait' declared here
static int ThreadBarrierWait(ThreadBarrier *barrier)
           ^
./ThreadPthread.h:36:28: error: use of undeclared identifier 'PTHREAD_BARRIER_SERIAL_THREAD'
        return ret == 0 || ret == PTHREAD_BARRIER_SERIAL_THREAD;
                                  ^
./ThreadPthread.h:41:9: error: no matching function for call to 'pthread_setname_np'
        return pthread_setname_np(thread, name) == 0;
               ^~~~~~~~~~~~~~~~~~
/usr/include/pthread.h:475:5: note: candidate function not viable: requires 1 argument, but 2 were
      provided
int     pthread_setname_np(const char*);
        ^
7 errors generated.

Patch-set: 7
Label: Verified=0