[dsf-gdb] BaseTestCase: clear line tags before each test run
When a test marked with Intermittent fails, the next retry is executed
with the same class instance.  Therefore, the new try starts with a
non-empty fTagLocations.  The test trips on the check that there are no
duplicate tags.

The fix I suggest is to add a @Before method in BaseTestCase to clear
fTagLocations.

This is the error I am seeing:

java.lang.RuntimeException: Tag FIRST_LINE_IN_MAIN was found twice in LaunchConfigurationAndRestartTestApp.cc
	at org.eclipse.cdt.tests.dsf.gdb.framework.BaseTestCase.resolveLineTagLocations(BaseTestCase.java:360)
	at org.eclipse.cdt.tests.dsf.gdb.tests.LaunchConfigurationAndRestartTest.doBeforeTest(LaunchConfigurationAndRestartTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.eclipse.cdt.tests.dsf.gdb.framework.IntermittentRule$RunIntermittent.evaluate(IntermittentRule.java:71)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

Change-Id: If4c28557eac7ee740b4e3a5eac5dd2726c39a35d
Signed-off-by: Simon Marchi <simon.marchi@polymtl.ca>