Update patch set 2
Patch Set 2:

> https://ci.eclipse.org/cdt/job/cdt-verify-test-cdt-other-pipeline/2884/ : UNSTABLE

I have retriggered this build in case one of our unstable tests failed, however one of the test failures was unfamiliar to me and I would guess a regression:

org.eclipse.cdt.internal.index.tests.IndexIncludeTest.testPragmaOnceChange (from org.eclipse.cdt.core.suite.AutomatedIntegrationSuite)

Error Message
expected:<3> but was:<1>
Stacktrace
junit.framework.AssertionFailedError: expected:<3> but was:<1>
	at org.eclipse.cdt.internal.index.tests.IndexIncludeTest.testPragmaOnceChange(IndexIncludeTest.java:634)

Patch-set: 2