Update patch set 1
Patch Set 1:

What do you think about this?
I guess it's big enough for a ticket and I will create one tomorrow.

Today, I came across a log entry that looked like this:

!ENTRY org.eclipse.cdt.core 4 0 2021-04-05 09:38:14.358
!MESSAGE Error: Cannot run program "make": ¾׼¼½º°¡ °źεǾ
!STACK 0
java.io.IOException: Cannot run program "make": ¾׼¼½º°¡ °źεǾ
at org.eclipse.cdt.utils.spawner.Spawner.exec(Spawner.java:352)
at org.eclipse.cdt.utils.spawner.Spawner.<init>(Spawner.java:94)
at org.eclipse.cdt.utils.spawner.ProcessFactory.exec(ProcessFactory.java:91)
at org.eclipse.cdt.core.CommandLauncher.execute(CommandLauncher.java:193)
at org.eclipse.cdt.core.CommandLauncherManager$CommandLauncherWrapper.execute

It appears that ThrowNew() expects the message argument to be encoded in UTF-8 and that works as long as you are on an English version of Windows as it's using ASCII that is a sub-set of UTF-8, but other versions of Windows will get "random" encoding when calling FormatMessageA().

I've tried to fix the encoding and also prefix the string with the value that GetLastError() returned to make it easier to lookup the error if it's not logged in English.

Do you have any idea on how to test this?
I supposed that a Chinese windows installation, or something that does not bring in the English language pack, would work, but I do not have any such installations that I test on. Do you have access to a system that does not have English Windows that would be sufficient for the test?
Or would you rather go for the if-it-compiles-it-works approach and let our users report any potential issues?

Patch-set: 1
Reviewer: Gerrit User 27769 <27769@97ee7c02-f12f-4043-b43e-dea463d88b31>